telegram app data:
    id: 29...
    hash: ab96...
imgur api: 
    # Leave as false to skip image forwarding
    id: c08...
    secret: bb44...
channels:
    1846...: https://discord.com/api/webhooks/...

